#cloud-config

packages:
  - unzip
# - default-jdk # jsp
  - tomcat7
# - tomcat7-admin


write_files:
# sshconf
- path: /home/prometheus/.ssh/authorized_keys
  content: |
    ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnRMDhongUg0DarYUEAHymX5UDc8Q/jy0u78ubGInrQKNgqItd6+GVV5I43YSuww4R2sIOeNu39sEPkD0DtqRrXFIA4m8exX5f3W+bg+JVRn2WUodh2LNfOZg574sxz2cWoAavqdomSPUG/w2x4DFCy37GlR2ztaN5/1Poz4V3uXShAmXUKjYz829jhWP5/5fcOl6g/B+N2yawd4IxeJvumz+c+r3AjQYIdkr0vz8OdmHbMkPOOzoSBHxhKq0/4NgzIim1tlJZWMN2ZPQZ7sLdU05Yx3+1tnDuy4VDFn2pZj0WL18fq1arzMKLtU1dcnXEJPyqwZsNkm9oDJF5MdFQw==

# consul config
- content: |
    {
    "server": false,
    "datacenter": "dataavenue",
    "data_dir": "/var/consul",
    "encrypt": "uohStneoKEoVYZIASGp6Nw==",
    "log_level": "INFO",
    "enable_syslog": true,
    "retry_join": ["{{getip(variables.consul_host)}}"], 
    "rejoin_after_leave": true,
    "services": [{"name":"da_cluster","port":9100}]
    }
  path: /etc/consul.d/client/config.json
# consul da health check
- content: |
    {
      "check": {
      "id": "da-check",
      "name": "Data Avenue Status",
      "http": "http://localhost:8080/{{variables.da_webapp_name}}",
      "service_id" : "da_cluster",
      "interval": "60s",
      "timeout": "10s"
      }
    }
  path: /etc/consul.d/client/da.json
# service consul
- content: |
    [Unit]
    Description=description Consul agent
    Requires=network-online.target
    After=network-online.target

    [Service]
    EnvironmentFile=-/etc/sysconfig/consul
    Environment=GOMAXPROCS=2
    Type=simple
    ExecStart=/bin/sh -c "exec consul agent -config-dir /etc/consul.d/client"
    Restart=always
    [Install]
    WantedBy=multi-user.target

  path: /etc/systemd/system/consul.service
# set hostname
- content: |
    #!/bin/sh
    if [ $reason = "BOUND" ]; then
        oldhostname=$(hostname -s)
        if [ $oldhostname != $new_host_name ]; then
            # Rename Host
            echo $new_host_name > /etc/hostname
            hostname -F /etc/hostname
            # Update /etc/hosts if needed
            TMPHOSTS=/etc/hosts.dhcp.new
            if ! grep "$new_ip_address $new_host_name.$new_domain_name $new_host_name" /etc/hosts; then
                # Remove the 127.0.1.1 put there by the debian installer
                grep -v '127\.0\.1\.1 ' < /etc/hosts > $TMPHOSTS
                # Add the our new ip address and name
                echo "$new_ip_address $new_host_name.$new_domain_name $new_host_name" >> $TMPHOSTS
                mv $TMPHOSTS /etc/hosts
            fi
            # Recreate SSH2 keys
            export DEBIAN_FRONTEND=noninteractive 
            dpkg-reconfigure openssh-server
        fi
    fi
  path: /etc/dhcp/dhclient-exit-hooks.d/sethostname

 # node_exporter service
- path: /etc/systemd/system/node_exporter.service
  content: |
    [Unit]
    Description=prometheus service
    After=network.target

    [Service]
    Type=simple
    WorkingDirectory=/opt/prometheus
    EnvironmentFile=-/etc/default/prometheus
    ExecStart=/opt/prometheus/node_exporter > /opt/prometheus/node_exporter.log 
    KillMode=control-group
    Restart=always
    [Install]
    WantedBy=multi-user.target

runcmd:
# host: ubuntu
  - sudo dhclient
  - echo "{{getip(variables.consul_host)}} dataavenue.database" | tee -a /etc/hosts
# consul
  - sudo useradd consul
  - wget https://releases.hashicorp.com/consul/0.5.2/consul_0.5.2_linux_amd64.zip
  - unzip *.zip
  - rm *.zip
  - sudo cp consul /usr/local/bin/
# config
  - sudo mkdir /var/consul
  - sudo chown consul:consul /var/consul
  - sudo chown consul:consul /etc/consul.d/client
# bootstrap
  - sudo systemctl enable consul.service
# tomcat config
  - sed -i 's/^JAVA_OPTS=.*$/JAVA_OPTS="-Xmx1024m -XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC"/' /etc/default/tomcat7
  - sudo chown tomcat7:tomcat7 /usr/share/tomcat7
  - sudo service tomcat7 restart
  - wget --no-check-certificate -O /var/lib/tomcat7/webapps/{{variables.da_webapp_name}}.war https://dataavenue.s3.lpds.sztaki.hu/blacktop3.war
  - mkdir /opt/prometheus/
  - wget https://github.com/prometheus/node_exporter/releases/download/0.12.0/node_exporter-0.12.0.linux-amd64.tar.gz -O node_exporter.tar.gz
  - tar -xvzf node_exporter.tar.gz
  - cp node_exporter-0.12.0.linux-amd64/node_exporter /opt/prometheus/
  - chown -R prometheus:prometheus /opt/prometheus/ 
  - sudo systemctl enable node_exporter.service
  - sudo systemctl start node_exporter.service
  - sudo systemctl start consul.service
