#cloud-config

# packages
packages:
# - mc
  - unzip # for consul agent
  - haproxy

# haproxy repository
apt_sources:
- source: "ppa:vbernat/haproxy-1.5"

# apt-get update
apt_update: true

# files
write_files:
# sshconf
- path: /home/prometheus/.ssh/authorized_keys
  content: |
    ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnRMDhongUg0DarYUEAHymX5UDc8Q/jy0u78ubGInrQKNgqItd6+GVV5I43YSuww4R2sIOeNu39sEPkD0DtqRrXFIA4m8exX5f3W+bg+JVRn2WUodh2LNfOZg574sxz2cWoAavqdomSPUG/w2x4DFCy37GlR2ztaN5/1Poz4V3uXShAmXUKjYz829jhWP5/5fcOl6g/B+N2yawd4IxeJvumz+c+r3AjQYIdkr0vz8OdmHbMkPOOzoSBHxhKq0/4NgzIim1tlJZWMN2ZPQZ7sLdU05Yx3+1tnDuy4VDFn2pZj0WL18fq1arzMKLtU1dcnXEJPyqwZsNkm9oDJF5MdFQw==

  # DHCP hook
- path: /etc/dhcp/dhclient-exit-hooks.d/sethostname
  content: |
    #!/bin/sh
    if [ $reason = "BOUND" ]; then
        oldhostname=$(hostname -s)
        if [ $oldhostname != $new_host_name ]; then
            # Rename Host
            echo $new_host_name > /etc/hostname
            hostname -F /etc/hostname
            # Update /etc/hosts if needed
            TMPHOSTS=/etc/hosts.dhcp.new
            if ! grep "$new_ip_address $new_host_name.$new_domain_name $new_host_name" /etc/hosts; then
                # Remove the 127.0.1.1 put there by the debian installer
                grep -v '127\.0\.1\.1 ' < /etc/hosts > $TMPHOSTS
                # Add the our new ip address and name
                echo "$new_ip_address $new_host_name.$new_domain_name $new_host_name" >> $TMPHOSTS
                mv $TMPHOSTS /etc/hosts
            fi
            # Recreate SSH2 keys
            export DEBIAN_FRONTEND=noninteractive 
            dpkg-reconfigure openssh-server
        fi
    fi
  
  # Consul config
- path: /etc/consul.d/client/config.json
  content: |
    {
    "server": false,
    "datacenter": "dataavenue",
    "data_dir": "/var/consul",
    "encrypt": "uohStneoKEoVYZIASGp6Nw==",
    "log_level": "INFO",
    "enable_syslog": true,
    "retry_join": ["{{getip(variables.consul_host)}}"], 
    "rejoin_after_leave": true,
    "services": [{"name": "lb_cluster","port": 9100}]
    }

  # Consul service
- content: |
    [Unit]
    Description=description Consul agent
    Requires=network-online.target
    After=network-online.target

    [Service]
    EnvironmentFile=-/etc/sysconfig/consul
    Environment=GOMAXPROCS=2
    Type=simple
    ExecStart=/bin/sh -c "exec consul agent -config-dir /etc/consul.d/client"
    Restart=always
    [Install]
    WantedBy=multi-user.target

  path: /etc/systemd/system/consul.service
  # HAProxy config
- path: /etc/haproxy/haproxy.cfg
  content: |
    global 
      maxconn 2048
      tune.ssl.default-dh-param 2048
      log 127.0.0.1 local1 notice
    defaults
      log global
      timeout connect 5000
      timeout client  36000000
      timeout server  36000000
      option http-server-close
    frontend http-frontend
      bind {{address}}:80
      default_backend dataavenue
    frontend https-frontend
      bind {{address}}:443 ssl crt /etc/ssl/private/mypem.pem
      reqadd X-Forwarded-Proto:\ https
      default_backend dataavenue
    backend dataavenue
      redirect scheme https if !{ ssl_fc }
      server da1 192.168.152.210:8080

  # Consul-template template
- path: /etc/haproxy/haproxy.ctmpl
  content: |
    global 
      maxconn 2048
      tune.ssl.default-dh-param 2048
      log 127.0.0.1 local1 notice
    defaults
      log global
      timeout connect 5000
      timeout client  36000000
      timeout server  36000000
      option http-server-close
    frontend http-frontend
      bind {{address}}:80
      default_backend dataavenue
    frontend https-frontend
      bind {{address}}:443 ssl crt /etc/ssl/private/mypem.pem
      reqadd X-Forwarded-Proto:\ https
      default_backend dataavenue
    backend dataavenue
      redirect scheme https if !{ ssl_fc }
      balance leastconn {{'{{'}}range service "da_cluster"{{'}}'}}
      server {{'{{'}}.Node{{'}}'}} {{'{{'}}.Address{{'}}'}}:8080{{'{{'}}end{{'}}'}}

  # Consul-template service
- path: /etc/systemd/system/consul-template.service
  content: |
    [Unit]
    Description=Consul-template
    Requires=network-online.target
    After=network-online.target

    [Service]
    EnvironmentFile=-/etc/sysconfig/consul
    Environment=GOMAXPROCS=2
    Type=simple
    ExecStart=/bin/sh -c "exec consul-template -consul {{ibget('node.resource.address', find_node_id(variables.consul_host))}}:8500 -template "/etc/haproxy/haproxy.ctmpl:/etc/haproxy/haproxy.cfg:service haproxy reload""
    Restart=always
    [Install]
    WantedBy=multi-user.target

# node_exporter service
- path: /etc/systemd/system/node_exporter.service
  content: |
    [Unit]
    Description=prometheus service
    After=network.target

    [Service]
    Type=simple
    WorkingDirectory=/opt/prometheus
    EnvironmentFile=-/etc/default/prometheus
    ExecStart=/opt/prometheus/node_exporter > /opt/prometheus/node_exporter.log 
    KillMode=control-group
    Restart=always
    [Install]
    WantedBy=multi-user.target

# Run once
# bootcmd:

# Run on restart
runcmd:
  # update hostname, /etc/hosts
- sudo dhclient
  # SSL host certificate
- openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mykey.key -subj "/C=HU/ST=HU/L=Budapest/O=SZTAKI LPDS/CN=Data Avenue" -out mycert.crt
- cat mycert.crt mykey.key > mypem.pem
- sudo cp mypem.pem /etc/ssl/private/
  # HAProxy logging
- echo "\$ModLoad imudp" | sudo tee -a /etc/rsyslog.conf
- echo "\$UDPServerAddress 127.0.0.1" | sudo tee -a /etc/rsyslog.conf
- echo "\$UDPServerRun 514" | sudo tee -a /etc/rsyslog.conf
- restart rsyslog
  # Consul-template install
- wget https://releases.hashicorp.com/consul-template/0.11.1/consul-template_0.11.1_linux_amd64.zip
- unzip consul-template_0.11.1_linux_amd64.zip
- sudo cp consul-template /usr/local/bin/
  # Consul-template start
- sudo systemctl enable consul-template.service
  # Consul install
- wget https://releases.hashicorp.com/consul/0.5.2/consul_0.5.2_linux_amd64.zip
- unzip consul_0.5.2_linux_amd64.zip
- sudo cp consul /usr/local/bin/
  # Consul config
- sudo mkdir /var/consul
- sudo useradd consul
- sudo chown consul:consul /var/consul
- sudo chown consul:consul /etc/consul.d/client
  # Consul service
- sudo systemctl enable consul.service
- mkdir /opt/prometheus/
- wget https://github.com/prometheus/node_exporter/releases/download/0.12.0/node_exporter-0.12.0.linux-amd64.tar.gz -O node_exporter.tar.gz
- tar -xvzf node_exporter.tar.gz
- cp node_exporter-0.12.0.linux-amd64/node_exporter /opt/prometheus/
- chown -R prometheus:prometheus /opt/prometheus/ 
- sudo systemctl enable node_exporter.service
- sudo systemctl start node_exporter.service
- sudo systemctl start consul.service
- sudo systemctl start consul-template.service
